### ISSUE TITLE
com.mongodb.CommandFailureException

### ISSUE THREAD

**Issue by michaelHampel** [ironfish/akka-persistence-mongo#93] opened 2015-06-29 19:44 UTC
Hello,

when using the latest release with MongoDB 2.6.7/2.6.8 we sometimes get an
com.mongodb.CommandFailureException: { "serverUsed" : "127.0.0.1:27017" , "ok" : 0 , "code" : 16 , "errmsg" : "no write ops were included in the batch"}

According to https://groups.google.com/forum/#!topic/mongodb-user/J11e_WblPhk this happens when
inserting an empty Set.
This is easily fixed in CasbahJournal's journal writeMessage method by only inserting the batch when it is not empty.
(Don't know if this maybe is better fixed in Casbah/Mongo Java Driver?)
This also happens when running your test suite, though all tests succeed so I guess the error has no "real" impact - but what I can't figure out why batch could be empty - writeMessages should only called when an event gets persisted?

thanks in advance,

michael

**Comment by ironfish** [comment] 2015-06-30 22:59
Do you know when this is happening? In other words is it on startup or while you are processing messages. The only way that you would have an empty `immutable.Seq[PersistentRepr]` in `writeMessages` is if you were trying to persist a "non-persistable" message.

**Comment by michaelHampel** [comment] 2015-07-03 09:34
The reocurring pattern is:
An exception occurs in receiveCommand of the PersistentActor and then the writeMessage gets an
empty Seq[PersistentRepr].
You can easily test this with your CasbahLoadSpec (had to update embeddedMongo to 1.48.0 to
set val version = Version.V2_6_8 in EmbeddedMongoSupport)

thanks,

michael

**Comment by ironfish** [comment] 2015-07-31 20:50
I will be pushing a significant update shortly so let's see if this problem persists.

**Comment by ironfish** [comment] 2015-08-03 15:02
I could not reproduce this error with the current commit which tests against embedded Mongo 3.x. Please try and reproduce and let me know if the error persists.

**Comment by btu** [comment] 2015-10-06 03:59
Hello,
It seems that when using defer function, most likely together with a persistAsync, it may create this issue.
Also, even though it doesn't seems to have consequences of its own, I noticed a correlation between persistence error and appearance of the "no write ops were included in the batch" error.

**Comment by ironfish** [comment] 2016-01-05 04:04
@michaelHampel and @btu try the new version [1.0.0-SNAPSHOT](https://github.com/ironfish/akka-persistence-mongo). It is fully asynchronous. I'm going to close this issue for now. Feel free to reopen if the problem persists.

**Closed by ironfish** 2016-01-05 04:04 UTC
